the table is added for the search results
bonny-art/code-crafters-tp-01 pull request #27
Opened 2024-08-15 05:53 UTC by MarynaKip

search results presents in the table

2024-08-15 16:59 UTC, bonny-art requested changes

2024-08-15 16:59 UTC, bonny-art commented on bot/cli/handlers.py
> -    if not matches:
треба додати перевірку на наявність аргументів. якщо немає - видавати помилку та підказку, як правильно використовувати команду якщо є - то об'єднати всі в рядок і тоді вже по ньому шукати. щось оп типу такого:
if len(args) == 0:
        raise ValueError("No note text provided.")
    note = Note(" ".join(args))
    
бо зараз якщо написати просто команду і забути щось додати - не дуже зрозуміла помилка. плюс якщо ввести більше одного слова - до уваги береться тільки перше. також не ок.

2024-08-15 17:56 UTC, bonny-art requested changes

2024-08-15 17:56 UTC, bonny-art commented on bot/cli/handlers.py
> +    elif len(args) > 1:
Я думаю, що не треба забороняти вводити більше одного слова. А краще зробити об'єднання всіх аргументів в один рядок через пробіл і шукати весь рядок.

Перероби, будь ласка, як буде час, таким чином.

2024-08-16 05:54 UTC, MarynaKip commented on bot/cli/handlers.py
> +    elif len(args) > 1:
Updated for multiple search inputs

2024-08-16 19:47 UTC, bonny-art approved these changes

2024-08-16 19:47 UTC, merged